---
# 缓存实例名，对应 @CacheConfig中的cacheNames。可以做的这种基本的过期时间差异化
elSysMap:
  #  过期时间24分钟
  ttl: 1440000
  #  最长空闲时间12分钟
  maxIdleTime: 720000
#  最大大小
#  maxSize: 0

user:
  ttl: 1440000
  maxIdleTime: 720000

